dependencies:
  - "OpenZeppelin/openzeppelin-contracts@4.5.0"
  - "smartcontractkit/chainlink@1.2.1"
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0" 
      - "@chainlink=smartcontractkit/chainlink@1.2.1"
dotenv: .env
networks:
  development:
    weth_token:
  kovan:
    weth_token: "0xd0A1E359811322d97991E03f863a0C30C2cF029C"
    fau_token: "0xFab46E002BbF0b4509813474841E0716E6730136"
    dai_usd_price_feed: "0x777A68032a88E5A84678A77Af2CD65A7b3c0775a"
    eth_usd_price_feed: "0x9326BFA02ADD2366b30bacB125260Af641031331" 
  rinkeby:
    weth_token: "0xc778417E063141139Fce010982780140Aa0cD5Ab"
  mainnet-fork:  
    weth_token: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"    
wallets:
  from_key: ${PRIVATE_KEY}    